resourcePackages:
- io.goobi.viewer.api.rest
prettyPrint: true
openAPI:
   basePath: "/api/v1"
   info:
      title: Goobi viewer API.
      description: This documentation describes the Goobi viewer API.
      license:
          name: GPL2 or later
          url: https://github.com/intranda/goobi-viewer-core/blob/master/LICENSE
readAllResources: false
ignoredRoutes:
   - /footer
   - /{type}
   - /status
   - /redirect/toFirstWork
