resourcePackages:
- io.goobi.viewer.servlets.rest
prettyPrint: true
openAPI:
   info:
      title: Goobi viewer REST API endpoints and schemas
      description: All endpoints available...
ignoredRoutes:
   - /rest/footer
   - /rest/ics
   - /rest/{type}
   - /rest/status
   - /rest/redirect/toFirstWork
